coilhq/web-monetization-projects

- package.json
- packages/coil-extension/package.json
- packages/coil-monorepo-upkeep/src/commands/doCheckUpdates.ts
- packages/coil-oauth-scripts/package.json
- packages/web-monetization-demo/package.json
- packages/web-monetization-polyfill-utils/package.json
- yarn.lock
* web-monetization: @types/node: ^12.12.5
* web-monetization-polyfill-utils: @types/node-fetch: ^2.5.3
* coil-extension: @types/node-fetch: ^2.5.3
* coil-oauth-scripts: @types/node-fetch: ^2.5.3
* web-monetization-demo: ilp-protocol-stream: ^2.2.0
* web-monetization-demo: @types/express: ^4.17.2
> feat: update dependencies

- packages/coil-extension/src/background/services/Stream.ts
- packages/coil-oauth-scripts/src/Stream.ts
The server isn't doing anything with it so should be removed
> feat: remove tier from btp server query string

- packages/coil-extension/test/puppeteer/basic-test.ts
- packages/coil-extension/test/puppeteer/testUrls.ts
Related to https://github.com/coilhq/coil/issues/2833
> feat(coil-extension): disable youtube tests

- packages/coil-extension/src/background/services/Stream.ts
Previously, rapidly switching between monetized tabs could trigger an assortment of errors (e.g. `TypeError: Cannot read property 'isOpen' of undefined`, `Unhandled error. (undefined)`, some timeouts, `Error: Unexpected error while sending packet. Code: F00, triggered by: [address], message: Cannot destructure property `userId` of 'undefined' or 'null'.`), and weird states (e.g. multiple simultaneous streams).
Preventing multiple streams from running simultaneously fixes the errors.
> fix(coil-extension): Stream race condition

- packages/coil-extension/src/background/services/Stream.ts
Changes per review: https://github.com/coilhq/web-monetization-projects/pull/90#pullrequestreview-319423397
> fix: code review refactor

- packages/coil-extension/src/background/background.ts
- packages/coil-extension/src/background/services/BackgroundStorageService.ts
- packages/coil-extension/src/content/content.ts
- packages/coil-extension/src/content/services/ContentAuthService.ts
- packages/coil-extension/src/content/services/ContentScript.ts
- packages/coil-extension/src/content/services/DomService.ts
- packages/coil-extension/src/content/services/Frames.ts
- packages/coil-extension/src/content/services/RunContentHandler.ts
- packages/coil-extension/src/content/util/adaptedRegex.ts
- packages/coil-extension/src/content/util/getAdaptedSite.ts
- packages/coil-extension/src/content/util/timeout.ts
- packages/web-monetization-wext/src/content/DocumentMonetization.ts
- packages/web-monetization-wext/src/content/IdleDetection.ts
- packages/web-monetization-wext/src/content/ScriptInjection.ts
- packages/web-monetization-wext/src/tokens.ts
Extension side of [coilhq/coil #2939](https://github.com/coilhq/coil/issues/2939).
> feat: query for payment pointer with channel URL

- packages/coil-extension/src/background/background.ts
- packages/coil-extension/src/background/services/BackgroundScript.ts
- packages/coil-extension/src/background/services/Stream.ts
- packages/coil-extension/src/background/services/Streams.ts
- packages/coil-extension/src/background/services/utils.ts
- packages/coil-extension/src/types/tokens.ts
Create custom logger and use in background page rather than using visionmedia/debug which loses the line numbers.
> feat(coil-extension): inject logger into background, fix #143

- packages/coil-extension/src/background/services/BackgroundStorageService.ts
- packages/coil-extension/src/background/services/PopupBrowserAction.ts
- packages/coil-extension/src/background/services/TabOpener.ts
- packages/coil-extension/src/util/openTab.ts
type WextApi alias of window.chrome causes issues with intellij
> feat(coil-extension): do not use WextApi alias

- packages/coil-extension/package.json
- packages/coil-extension/src/background/services/Stream.ts
- packages/coil-oauth-scripts/package.json
- packages/coil-oauth-scripts/src/Stream.ts
- packages/interledger-minute-extension/package.json
- packages/web-monetization-demo/package.json
- yarn.lock
May as well hold off on releasing this until it includes https://github.com/interledgerjs/ilp-protocol-stream/pull/124.
> perf: slippage=1, fixed exchangeRate,maximumPacketAmount

- packages/coil-extension/src/content/services/RunContentHandler.ts
Finishes up extension side of [coilhq/coil#2939](https://github.com/coilhq/coil/issues/2939) and closes #149.
> feat(coil-extension): use channelId in adapted query

- package.json
- packages/coil-extension/package.json
- packages/interledger-minute-extension/package.json
- packages/web-monetization-demo/package.json
- yarn.lock
* web-monetization: eslint: ^6.8.0
* web-monetization: typescript: 3.7.4
* web-monetization-demo: @types/react: ^16.9.17
* coil-extension: @types/react: ^16.9.17
* interledger-minute-extension: @types/react: ^16.9.17
> feat: upkeep dependencies

- package.json
- packages/coil-extension/docs/release-checklist.md
- packages/coil-extension/src/background/services/Stream.ts
- packages/coil-oauth-scripts/src/Stream.ts
- yarn.lock
This reverts commit b1ada22cdb3cc27fc0bf2b50dec17af08630be98.
> Revert "perf: slippage=1, fixed exchangeRate,maximumPacketAmount (#187)"

- packages/coil-extension/src/popup/components/CoilExplore.tsx
- packages/coil-extension/src/popup/components/MonetizedPage.tsx
- packages/coil-extension/src/popup/components/Unsubscribed.tsx
- packages/coil-extension/src/popup/components/WebMonetizedBar.tsx
Extension side of https://github.com/coilhq/coil/pull/2821
> feat(coil-extension): update popup copy

- packages/coil-extension/src/popup/components/MonetizedPage.tsx
- packages/coil-extension/src/popup/mocks/loadMockedStates.tsx
Closes: https://github.com/coilhq/web-monetization-projects/issues/385
> feat(coil-extension): remove 'Coil is paying creator' unless adapted

- packages/coil-anonymous-tokens/src/lib/privacypass/hashToCurve.ts
Apply https://github.com/privacypass/challenge-bypass-extension/pull/169
> fix(coil-extension): take privacypass/challenge-bypass-extension#169

- package.json
- yarn.lock
This reverts commit 338464b1be071b6a65cbce4a32b1e4130705e597.
> Revert "chore(deps-dev): bump @types/node from 12.12.50 to 13.13.15 (#870)"

- packages/coil-extension/src/popup/components/TipButton.tsx
> fix(coil-extension): show disabled tipping button while fetching fx rate

- packages/coil-anonymous-tokens/test/tsconfig.json
- packages/coil-client/test/tsconfig.json
- packages/coil-extension/test/tsconfig.json
- packages/coil-extension/tsconfig.debug.json
- packages/coil-monorepo-upkeep/templates/static-shared-duplicated/test/tsconfig.json
- packages/coil-monorepo-upkeep/test/tsconfig.json
- packages/coil-oauth-scripts/test/tsconfig.json
- packages/coil-playwright-utils/test/tsconfig.json
- packages/coil-polyfill-utils/test/tsconfig.json
- packages/coil-privacypass-sjcl/test/tsconfig.json
- packages/coil-webpack-utils/test/tsconfig.json
- packages/coil-wm-utils/test/tsconfig.json
- packages/dier-makr-annotations/test/tsconfig.json
- packages/dier-makr-inversify/test/tsconfig.json
- packages/interledger-minute-extension/test/tsconfig.json
- packages/interledger-minute-extension/tsconfig.debug.json
- packages/web-monetization-demo/test/tsconfig.json
- packages/web-monetization-polyfill-utils/test/tsconfig.json
- packages/web-monetization-react/test/tsconfig.json
- packages/web-monetization-testing-utils/test/tsconfig.json
- packages/web-monetization-types/test/tsconfig.json
- packages/web-monetization-wext/test/tsconfig.json
- packages/webexts-build-utils/test/tsconfig.json
- tsconfig.settings.json
https://jestjs.io/docs/en/ecmascript-modules
> feat: use es2020, closes #1268

- packages/coil-extension/scripts/build-coil-dev.sh
- packages/coil-extension/src/background/services/BackgroundScript.ts
- packages/coil-extension/src/popup/Index.tsx
- packages/coil-extension/src/popup/services/PopupState.ts
- packages/coil-extension/src/types/BuildConfig.ts
- packages/coil-extension/src/types/storage.ts
> feat(coil-extension): add popup footer string build config

- packages/coil-extension/src/popup/components/HeaderFooterLayout.tsx
- packages/coil-extension/src/popup/components/StatusButton.tsx
- packages/coil-extension/src/popup/components/views/CoilExploreView.tsx
- packages/coil-extension/src/popup/components/views/CoilPopupView.tsx
- packages/coil-extension/src/shared-theme/theme.ts
> fix(coil-extension): fix button color, rm dropshadow

- packages/coil-extension/src/popup/components/AmountInput.tsx
- packages/coil-extension/src/popup/components/CtaButton.tsx
- packages/coil-extension/src/popup/components/HotkeyAmountButtons.tsx
- packages/coil-extension/src/popup/components/IncDecButton.tsx
- packages/coil-extension/src/popup/components/Link.tsx
- packages/coil-extension/src/popup/components/LinkUnderlined.tsx
- packages/coil-extension/src/popup/components/NavBar.tsx
- packages/coil-extension/src/popup/components/TipAmountFeedback.tsx
- packages/coil-extension/src/popup/components/TipPaymentDebits.tsx
- packages/coil-extension/src/popup/components/views/Router.tsx
- packages/coil-extension/src/popup/components/views/StreamingCoilView.tsx
- packages/coil-extension/src/popup/components/views/StreamingNoMembershipView.tsx
- packages/coil-extension/src/popup/components/views/TipCompleteView.tsx
- packages/coil-extension/src/popup/components/views/TipConfirmView.tsx
- packages/coil-extension/src/popup/components/views/TipNonMonetizedView.tsx
- packages/coil-extension/src/popup/components/views/TipView.tsx
- packages/coil-extension/src/popup/context/tipContext.tsx
- packages/coil-extension/src/popup/mocks/loadMockedStates.tsx
- packages/coil-extension/src/shared-theme/theme.ts
- packages/coil-extension/src/types/user.ts
- packages/coil-extension/src/util/getCreditCardFromPaymentMethods.ts
resolves: COIL-1568
- Created a `TipAmountFeedback` to update the user on their tip state
- Restricted tipping inputs based on maximum allowable tip limit
- Created a non monetized tipping view
- Several minor style issues
> feat: tip limit restrictions

- packages/coil-extension/src/popup/components/views/StreamingCoilView.tsx
> fix: extension does not show any UI on coil site

- .pnp.cjs
- packages/coil-extension/package.json
- yarn.lock
This reverts commit 86c7c7d9c035b023a7eff268e598bc691b47648b.
> Revert "fix(deps): update dependency framer-motion to v6 (#2528)"

- packages/coil-extension/src/background/consts/AssetConstants.ts
- packages/coil-extension/src/background/services/TippingService.ts
update the emitted event for tip to reflect the correct assetCode and assetScale
> feat: added constants for tip assetcode assetscale

- packages/coil-extension/src/background/services/BackgroundScript.ts
- packages/coil-extension/src/background/services/TippingService.ts
- packages/coil-extension/src/popup/components/views/TipView.tsx
- packages/coil-extension/src/types/commands.ts
resolves: COIL-1810
added command to update the tipping settings data when the tip view is loaded.
> feat: update tip settings on initial tip view

- packages/coil-extension/src/popup/components/AmountInput.tsx
- packages/coil-extension/src/popup/components/TipAmountFeedback.tsx
resolves: COIL-1842
If the remaining daily limit is less than the minimum tip limit, show updated feedback for user.
> feat: added feedback for daily limit being below min tip

- packages/coil-extension/src/popup/components/IncDecButton.tsx
resolves: COIL-1838
delay the initial change of the amount with the + - buttons are used.
> feat: delayed inc dec adjustment on click

- packages/coil-extension/src/popup/components/AmountInput.tsx
resolves: COIL-1713
The tipping view manual input no longer accepts leading zeros, leading decimals, special characters, or alphabet characters.
> feat: fix amount input

- packages/coil-extension/manifest.json
Updates the manifest to version 0.0.57 for the release.
> feat: update manifest to 0.0.57 for release

- packages/coil-extension/src/popup/components/AmountInput.tsx
- packages/coil-extension/src/popup/components/Header.tsx
- packages/coil-extension/src/popup/components/IncDecButton.tsx
- packages/coil-extension/src/popup/components/Link.tsx
- packages/coil-extension/src/popup/components/LinkUnderlined.tsx
- packages/coil-extension/src/popup/components/NavBar.tsx
- packages/coil-extension/src/popup/components/TipAmountFeedback/RestrictedMessage.tsx
- packages/coil-extension/src/popup/components/views/SettingsView.tsx
- packages/coil-extension/src/popup/components/views/StreamingNotWebMonetizedView.tsx
resolves: COIL-1889
Added keyboard accessiblility for the buttons and input on the extension
> feat: keyboard accessible buttons

- packages/coil-extension/src/popup/Index.tsx
- packages/coil-extension/src/popup/context/routerContext.tsx
resolves: COIL-1983
set the default extension view to tipping if the user is allowed to tip
> feat: set default view to tip view if allowed

- packages/coil-extension/docs/release-checklist.md
- packages/coil-extension/src/background/services/AuthService.ts
- packages/coil-extension/src/background/services/BackgroundScript.ts
- packages/webexts-build-utils/src/copyToDist.ts
- packages/webexts-build-utils/src/env.ts
- packages/webexts-build-utils/src/reloadServer.ts
- packages/webexts-build-utils/src/transformManifest.ts
- packages/webexts-build-utils/src/types/manifest.ts
* do not check if logged out on startup to minimize opening a tab to get token
* do not bundle hot-reload.js when built for mv3
* allow setting WEXT_MANIFEST_INCOGNITO
* add incognito field to manifest type etc
> feat(coil-extension): tweak mv3 behavior

- packages/coil-extension/CHANGELOG.md
- packages/coil-extension/manifest.json
- packages/coil-extension/package.json
https://github.com/coilhq/web-monetization-projects/compare/coil-extension@0.0.61...nd-bump-version-62-2022-09-21
> chore(coil-extension): bump version to 0.0.62

- packages/coil-extension/src/background/services/BackgroundScript.ts
- packages/coil-extension/src/background/services/TabStates.ts
- packages/coil-extension/src/content/util/getAdaptedSite.ts
- packages/coil-extension/src/popup/components/views/StreamingNotWebMonetizedView.tsx
- packages/coil-extension/src/popup/mocks/loadMockedStates.tsx
- packages/coil-extension/src/popup/popup.tsx
- packages/coil-extension/src/popup/services/PopupState.ts
- packages/coil-extension/src/types/TabState.ts
- packages/coil-extension/src/types/storage.ts
See [popup preview](https://web-monetization-projects-1kwalmbmq-coilhq.vercel.app/static/popup.html)
Closes COIL-2711
> feat(coil-extension): disable twitch integration
