coilhq/web-monetization-projects

packages/coil-extension/docs/release-checklist.md, packages/coil-extension/manifest.json, packages/coil-extension/package.json, packages/coil-extension/src/background/services/BackgroundScript.ts, packages/coil-extension/src/background/services/TabStates.ts, packages/coil-extension/src/types/TabState.ts, packages/web-monetization-wext/src/content/IdleDetection.ts
simply opens settings.
- Install android-sdk on PC and Firefox on android
- Enable developer mode on android and enable usb debugging
- Plug in android to PC via usb    
- `adb devices # make note of device id`
- `adb shell pm grant org.mozilla.firefox android.permission.READ_EXTERNAL_STORAGE`
- `adb shell pm grant org.mozilla.firefox android.permission.WRITE_EXTERNAL_STORAGE`
- Build the extension
- `yarn web-ext run -s $PWD/dist --target=firefox-android --android-device=WUJ01PNSVY # from adb devices step` 
- Issue: [coil/coilhq#2084][ci2084]
- Fix PRs: [#166][p166] [#295][p295]
- For Chrome, go to …
=> chore(coil-extension): bump version to 0.0.40 for release

packages/coil-extension/manifest.json, packages/coil-extension/package.json, packages/coil-extension/test.sh, packages/coil-extension/test/puppeteer/basic-test.ts, packages/coil-extension/test/puppeteer/testUrls.ts
simply opens settings.
- Install android-sdk on PC and Firefox on android
- Enable developer mode on android and enable usb debugging
- Plug in android to PC via usb    
- `adb devices # make note of device id`
- `adb shell pm grant org.mozilla.firefox android.permission.READ_EXTERNAL_STORAGE`
- `adb shell pm grant org.mozilla.firefox android.permission.WRITE_EXTERNAL_STORAGE`
- Build the extension
- `yarn web-ext run -s $PWD/dist --target=firefox-android --android-device=WUJ01PNSVY # from adb devices step` 
- Issue: [coil/coilhq#2084][ci2084]
- Fix PRs: [#166][p166] [#295][p295]
- For Chrome, go to …
=> chore(coil-extension): bump version to 0.0.41 for release

packages/coil-extension/src/background/services/Stream.ts, packages/coil-oauth-scripts/src/Stream.ts
In ilp-protocol-stream, `Stream`s emit `"outgoing_money"` events before `connection.totalDelivered` is updated. This resulted in the extension ignoring the first `outgoing_money` event, since it mistakenly assumed that no money was delivered.
In my tests, this shortened the time-to-`monetizationstart` from 2500-2800ms down to 500-700ms.
=> perf: speed up monetizationstart

packages/coil-extension/docs/release-checklist.md, packages/coil-extension/manifest.json, packages/coil-extension/package.json, packages/coil-extension/test/fixtures/event-logger.html
simply opens settings.
- Install android-sdk on PC and Firefox on android
- Enable developer mode on android and enable usb debugging
- Plug in android to PC via usb
- `adb devices # make note of device id`
- `adb shell pm grant org.mozilla.firefox android.permission.READ_EXTERNAL_STORAGE`
- `adb shell pm grant org.mozilla.firefox android.permission.WRITE_EXTERNAL_STORAGE`
- Build the extension
- `yarn web-ext run -s $PWD/dist --target=firefox-android --android-device=WUJ01PNSVY # from adb devices step`
- Issue: [coil/coilhq#2084][ci2084]
- Fix PRs: [#166][p166] [#295][p295]
- e.g. `yarn build-prod firefox -p --run-prod --devtool=none`
- For Chrome, go to …
=> chore(coil-extension): bump version to 0.0.42

packages/coil-extension/src/content/util/getAdaptedSite.ts
Ensures that the extension will only query on video and channel pages, and not on pages like Youtube's homepage or search results pages. Part of [coilhq/coil#2939](https://github.com/coilhq/coil/issues/2939).
=> feat(coil-extension): use stricter regex for youtube urls

package.json, packages/coil-puppeteer-utils/package.json, yarn.lock
* web-monetization: @babel/core: ^7.7.7
* web-monetization: @babel/plugin-proposal-object-rest-spread: ^7.7.7
* web-monetization: @babel/preset-env: ^7.7.7
* web-monetization: @babel/preset-typescript: ^7.7.7
* web-monetization: @types/jest: ^24.0.24
* web-monetization: @types/node: ^12.12.21
* web-monetization: webpack-dev-server: ^3.10.0
* coil-puppeteer-utils: get-port: ^5.1.0
=> feat: upkeep dependencies

packages/coil-extension/CHANGELOG.md, packages/coil-extension/docs/release-checklist.md, packages/coil-extension/manifest.json, packages/coil-extension/package.json, packages/coil-extension/src/background/background.ts
`https://github.com/coilhq/web-monetization-projects/compare/coil-extension@0.0.43...df9abc06b3b1ece6098889446d1444fb9bd58dd7`
simply opens settings.
- Install android-sdk on PC and Firefox on android
- Enable developer mode on android and enable usb debugging
- Plug in android to PC via usb
- `adb devices # make note of device id`
- `adb shell pm grant org.mozilla.firefox android.permission.READ_EXTERNAL_STORAGE`
- `adb shell pm grant org.mozilla.firefox android.permission.WRITE_EXTERNAL_STORAGE`
- Build the extension
- `yarn web-ext run -s $PWD/dist --target=firefox-android --android-device=WUJ01PNSVY # from adb devices step`
- Issue: [coil/coilhq#2084][ci2084]
- Fix PRs: [#166][p166] [#295][p295]
- e.g. `yarn …
=> chore(coil-extension): bump version to 0.0.44

packages/coil-extension/CHANGELOG.md, packages/coil-extension/docs/release-checklist.md, packages/coil-extension/manifest.json, packages/coil-extension/package.json
`https://github.com/coilhq/web-monetization-projects/compare/coil-extension@0.0.43...df9abc06b3b1ece6098889446d1444fb9bd58dd7`
- For Chrome, go to `chrome://extensions` and `Load Unpacked`
- ![image](https://user-images.githubusercontent.com/525211/66626655-3c3aae80-ec23-11e9-981a-0e317ab80b42.png)
- …
=> chore(coil-extension): bump version to 0.0.45

package.json, packages/coil-extension/src/background/services/Stream.ts, packages/coil-oauth-scripts/src/Stream.ts, yarn.lock
The fixed exchange rate &c was reverted in 2babae5 to accommodate a GateHub race condition (see https://github.com/coilhq/coil/issues/3038) which is now fixed.
Closes https://github.com/coilhq/coil/issues/3038.
cc: @traviscrist
=> fix: re-enable slippage=1 and fixed exchangeRate,maxPacketAmount

packages/coil-extension/src/background/services/BackgroundScript.ts, packages/coil-extension/src/background/services/BackgroundStorageService.ts
Simply by accessing `chrome.runtime.lastError` we can avoid the console being littered with errors where messages are sent but no popup is open:
This aligns the behavior of Firefox with Chrome which silently ignores these errors.
=> feat(coil-extension): fix #175, ignore popup not exist errors

packages/coil-extension/package.json, packages/coil-extension/src/background/services/Stream.ts, yarn.lock
Ensure that payment succeeds in spite of a client's clock skew.
Send all Prepare packets with a fixed `expiresAt` in the far future (`2100-01-01T00:00:00.000Z`). The connector clamps that using the `maxHoldTime` (30s) before forwarding the Prepare.
Note that this includes https://github.com/interledgerjs/ilp-protocol-stream/pull/128 and https://github.com/interledgerjs/interledgerjs/pull/7.
Fixes https://github.com/coilhq/coil/issues/2903.
=> fix(coil-extension): fix clock skew

packages/coil-oauth-scripts/package.json, packages/interledger-minute-extension/package.json, packages/web-monetization-demo/package.json, yarn.lock
* web-monetization-demo: ilp-protocol-stream: ^2.3.0
* coil-oauth-scripts: ilp-protocol-stream: 2.3.0
* interledger-minute-extension: ilp-protocol-stream: 2.3.0
=> feat: update ilp-protocol-stream

packages/coil-anonymous-tokens/src/index.ts, packages/coil-extension/package.json, packages/coil-extension/src/background/background.ts, packages/coil-extension/src/background/services/AnonymousTokens.ts, packages/coil-extension/src/background/services/Stream.ts, packages/coil-extension/src/types/tokens.ts, packages/coil-extension/src/webpackDefines.ts, packages/coil-extension/tsconfig.build.json, packages/coil-extension/webpack.dev.ts, packages/coil-extension/webpack.prod.ts, packages/coil-extension/webpack.staging.ts, yarn.lock
Note that this is a PR to `bs-anonymous-tokens`, not `master`. Some of these changes depend on https://github.com/coilhq/coil/pull/3071
Open questions:
* Right now to determine if a token is exhausted the extension checks for the substring `"exhausted capacity"` in the error message. Is that Good Enough or should a specific error code be selected (right now it uses `F00`)?
* What domains will the redeemer and signer services run on?
=> misc anonymous token updates

packages/coil-extension/CHANGELOG.md, packages/coil-extension/docs/release-checklist.md, packages/coil-extension/manifest.json, packages/coil-extension/package.json, packages/coil-extension/src/background/services/BackgroundScript.ts, packages/coil-extension/src/content/services/MonetizationEventsLogger.ts, packages/coil-extension/src/types/commands.ts, packages/web-monetization-wext/src/content/DocumentMonetization.ts
`https://github.com/coilhq/web-monetization-projects/compare/coil-extension@0.0.45...f9a9e78df4a1d40f225888a874b3850797c4eefe`
make sense. …
=> chore(coil-extension): bump version to 0.0.46

packages/coil-client/src/queries/whoAmI.ts, packages/coil-extension/src/background/services/AuthService.ts, packages/coil-extension/src/background/services/BackgroundScript.ts, packages/coil-extension/src/background/services/Stream.ts, packages/coil-extension/src/background/services/Streams.ts, packages/coil-extension/src/popup/components/MonetizedPage.tsx, packages/coil-extension/src/popup/components/TipButton.tsx, packages/coil-extension/src/types/commands.ts, packages/coil-extension/src/types/user.ts
For users enabled for tipping, this adds a button to the popup on Web Monetized pages. Right now it's an internal pilot that sends out one dollar at a time. This does not affect the experience for users on which `canTip` is not true (i.e. they aren't `@coil.com`)
=> feat: tipping preview

.circleci/config.yml, packages/coil-extension/manifest.json, packages/coil-extension/src/background/services/BackgroundFramesService.ts, packages/coil-extension/src/background/services/BackgroundScript.ts, packages/coil-extension/src/background/services/StreamAssociations.ts, packages/coil-extension/src/background/services/TabStates.ts, packages/coil-extension/src/background/services/YoutubeService.ts, packages/coil-extension/src/content/content.ts, packages/coil-extension/src/content/services/AdaptedContentService.ts, packages/coil-extension/src/content/services/ContentScript.ts, packages/coil-extension/src/content/services/Frames.ts, packages/coil-extension/src/content/util/isMonetizationAllowed.ts, packages/coil-extension/src/types/FrameSpec.ts, packages/coil-extension/src/types/TabState.ts, packages/coil-extension/src/types/commands.ts, packages/coil-extension/src/util/tabs.ts, packages/coil-extension/test/fixtures/iframes/frame1.html, packages/coil-extension/test/fixtures/iframes/frame2.html, packages/coil-extension/test/fixtures/iframes/frame3.html, packages/coil-extension/test/fixtures/iframes/index.html, packages/coil-oauth-scripts/src/MonetizationPolyfill.ts, packages/coil-puppeteer-utils/src/lib/testMonetization.ts, packages/web-monetization-polyfill-utils/src/index.ts, packages/web-monetization-polyfill-utils/src/lib/MonetizationTagObserver.ts, packages/web-monetization-polyfill-utils/src/lib/parsePolicyDirectives.ts, packages/web-monetization-polyfill-utils/test/jest/parsePolicyDirectives.test.ts, packages/web-monetization-wext/src/content/DocumentMonetization.ts
This pull request implements Web Monetization inside <iframe> elements. Only iframes that are direct children of the top frame, with monetization in their `allow` feature set policy will be monetized. 
It does this by changing the 1:1 mapping of WM streams to browser tabs to M:1, with the 1:1 mapping now of WM streams to iframes. 
To do so, it takes advantage of:
1. [webNavigation](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/webNavigation) wext apis 
* New BackgroundFrameService
* Keeps track of frames, including the current readyState/url/parentFrameId etc.
* use `frameChanged` event where using chrome.tabs.onUpdated before (which was [problematic](https://github.com/coilhq/web-monetization-projects/issues/203))
* Will require extra permissions which may be …
=> feat(coil-extension): add iframes impl

packages/coil-extension/CHANGELOG.md, packages/coil-extension/manifest.json, packages/coil-extension/package.json
`https://github.com/coilhq/web-monetization-projects/compare/coil-extension@0.0.43...df9abc06b3b1ece6098889446d1444fb9bd58dd7`
- ![image](https://user-images.githubusercontent.com/525211/66626655-3c3aae80-ec23-11e9-981 …
=> chore(coil-extension): bump version to 0.0.47

packages/coil-extension/src/background/services/AuthService.ts, packages/coil-extension/src/background/services/BackgroundFramesService.ts, packages/coil-extension/src/background/services/BackgroundScript.ts, packages/coil-extension/src/background/services/CachedOperations.ts, packages/coil-extension/src/background/services/Stream.ts, packages/coil-extension/src/background/util/flatMapSlow.ts, packages/coil-extension/src/content/services/ContentScript.ts, packages/coil-extension/src/content/services/Frames.ts, packages/coil-extension/src/content/util/isMonetizationAllowed.ts, packages/coil-extension/src/content/util/timeout.ts, packages/coil-extension/src/types/commands.ts, packages/coil-extension/test/fixtures/iframes/frame4.html, packages/coil-extension/test/fixtures/iframes/top-nested-allowed-iframe.html
This PR implements nested <iframe> support.
For an iframe to be monetized the allow feature set policy must include monetization in all parent frames.
For example, in the image above, the children inside `<iframe id="frame4copy">` (highlighted) will **NOT** monetize, while those in `<iframe id="frame4">` **WILL**. 
Some questions from the initial PR are still relevant:
https://github.com/coilhq/web-monetization-projects/pull/415
1. Open a terminal and `cd packages/coil-extension/test/fixtures/iframes/`
2. Start a server (via `python -m http.server 4000` or equivalent)
3. Open http://localhost:4000/top-nested-allowed-iframe.html in browser
4. Open developer tools and look at the structure of the dom
-  Use expand recursively feature
- …
=> feat(coil-extension): monetize nested iframes

packages/coil-extension/CHANGELOG.md, packages/coil-extension/docs/release-checklist.md, packages/coil-extension/manifest.json, packages/coil-extension/package.json
- ** TESTERS NOTE **
- chrome is currently rejected, stuck on version 0.47
`https://github.com/coilhq/web-monetization-projects/compare/coil-extension@0.0.43...df9abc06b3b1ece6098889446d1444fb9bd58dd7`
make sense.
- …
=> chore(coil-extension): bump version to 0.0.48

packages/coil-client/src/queries/queryToken.ts, packages/coil-client/src/queries/whoAmI.ts, packages/coil-client/src/types.ts, packages/coil-extension/src/background/services/AuthService.ts, packages/coil-extension/src/content/services/Frames.ts, packages/coil-extension/src/types/user.ts
Don't unnecessarily query the user/subscription -- wait until the subscription/trial expires. This is more efficient, and prevents correlation with token redeeming.
=> feat: dont unnecessarily query whoami

packages/coil-extension/CHANGELOG.md, packages/coil-extension/docs/release-checklist.md, packages/coil-extension/manifest.json, packages/coil-extension/package.json, packages/coil-extension/src/background/services/BackgroundScript.ts
`https://github.com/coilhq/web-monetization-projects/compare/coil-extension@0.0.48...8f359e45f843a4f9a01c090a02e73519413d900b`
- Some web stores will require the submission of source files.
- So far, zipping the `coil-extension` folder (instead of zipping at the project root)
has given us the least trouble with passing review.
- For example, `zip -r coil-extension.zip coil-extension/`
- `node_modules` should be deleted prior to zipping the source files.
- For Chrome or MS Edge, go to `chrome://extensions` (or `edge://extensions`) …
=> chore(coil-extension): bump version to 0.0.49

LICENSE.txt
Add the Apache 2.0 license to this repo since its open source and thats what we cite in the README.
=> chore: add Apache 2.0 license

packages/coil-extension/CHANGELOG.md, packages/coil-extension/docs/release-checklist.md, packages/coil-extension/manifest.json, packages/coil-extension/package.json, packages/coil-extension/src/popup/components/CoilPopup.tsx, packages/coil-extension/src/popup/components/TipButton.tsx, packages/coil-extension/src/popup/components/Unsubscribed.tsx, packages/coil-extension/src/popup/components/WebMonetizedBar.tsx
`https://github.com/coilhq/web-monetization-projects/compare/coil-extension@0.0.48...8f359e45f843a4f9a01c090a02e73519413d900b`
make sense. …
=> chore(coil-extension): bump version to 0.0.50

packages/coil-oauth-scripts/src/Stream.ts, packages/coil-oauth-scripts/src/bin/serve-it.ts, packages/web-monetization-demo/src/verifier/main.ts
How to test in only 5000 easy steps!
```
cd packages/coil-oauth-scripts
OUTPUT_TO=$PWD/../coil-extension/test/fixtures yarn build --watch
```
```
cd packages/web-monetization-demo
SERVER_PORT=4002 yarn run server:dev
```
```
cd packages/web-monetization-demo
SPSP_ENDPOINT=http://localhost:4002/spsp/~niq yarn run verifier:dev
```
```
cd packages/coil-oauth-scripts
export COIL_USER='*'
export COIL_PASSWORD='*'
SUBSTITUTES='{"$twitter.xrptipbot.com/Coil": "http://localhost:4001/spsp/~niq"}' \
POLYFILL_INIT_ARGS='{"btpEndpoint": "btp+ws://localhost:3000"}' \
yarn serve-it ../coil-extension/test/fixtures/event-logger.html
```
Load the page at http://localhost:4000
=> feat(coil-oauth-scripts): add receipts

README.md, packages/coil-anonymous-tokens/package.json, packages/coil-client/package.json, packages/coil-extension/package.json, packages/coil-monorepo-upkeep/package.json, packages/coil-monorepo-upkeep/src/commands/doUpKeep/doUpKeep.ts, packages/coil-monorepo-upkeep/src/types.ts, packages/coil-oauth-scripts/package.json, packages/coil-polyfill-utils/package.json, packages/coil-privacypass-sjcl/package.json, packages/coil-puppeteer-utils/package.json, packages/dier-makr-annotations/package.json, packages/dier-makr-inversify/package.json, packages/interledger-minute-extension/package.json, packages/web-monetization-demo/package.json, packages/web-monetization-polyfill-utils/package.json, packages/web-monetization-react/package.json, packages/web-monetization-types/package.json, packages/web-monetization-wext/package.json, packages/webexts-build-utils/package.json
Renames master to main. Locally devs should do the following to update their HEAD.
```
git checkout master
git branch -m master main
git fetch
git branch --unset-upstream
git branch -u origin/main
git symbolic-ref refs/remotes/origin/HEAD refs/remotes/origin/main
```
=> chore: rename main to master

packages/coil-extension/CHANGELOG.md, packages/coil-extension/manifest.json, packages/coil-extension/package.json
`https://github.com/coilhq/web-monetization-projects/compare/coil-extension@0.0.48...8f359e45f843a4f9a01c090a02e73519413d900b`
make sense. …
=> chore(coil-extension): bump version to 0.0.51

packages/coil-extension/safari/Coil/Coil.xcodeproj/project.pbxproj
I added the XCode project files to WM repo, using a ndudfield namespaced bundle id. It's been a while since I did any serious iOS ( edit: or ANY MacOS) dev, but iirc they register bundle-ids per dev. Would be nice/simpler to just commit a static bundle id to the repo.
=> feat(coil-extension): update safari bundleids

packages/coil-extension/scripts/publish-coildev-chrome-store.sh, packages/coil-extension/src/background/services/BackgroundScript.ts, packages/coil-extension/src/popup/components/AccountBar.tsx, packages/coil-extension/src/popup/services/PopupState.ts, packages/coil-extension/src/types/BuildConfig.ts, packages/coil-extension/src/types/storage.ts, packages/webexts-build-utils/src/makeWebpackConfig.ts
Webpack picks up WEXT_BUILD_CONFIG environment variable, expected to be json, this patch will check for `extensionBuildString` which if present will add a `Copy Build Info` menu item:
```
export WEXT_BUILD_CONFIG="{\"extensionBuildString\":\"$(git show --no-patch --no-notes --pretty='== %h == %cd == %s ==' )\"}"
```
=> feat(coil-extension): add publish-coildev-chrome-store.sh

packages/coil-extension/src/background/consts/Icons.ts, packages/coil-extension/src/background/services/PopupBrowserAction.ts
The previous fix wasn't quite right. After the xmas period was over, the Santa hat flickered until the extension was restarted, when the default icon was reset.
=> fix(coil-extension): set default icon every midnight, closes #1359

packages/coil-extension/src/content/services/ContentScript.ts, packages/web-monetization-wext/src/content/DocumentMonetization.ts, packages/web-monetization-wext/src/content/wmPolyfill.ts
CI *was* failing due to the `detail` property being restricted on CustomEvents on Firefox 
There seems to be potential workarounds listed here:
https://stackoverflow.com/questions/18744224/triggering-a-custom-event-with-attributes-from-a-firefox-extension
Simply sending detail as a string (JSON serialized object) seems to be simpler than using the cloneInto mentioned on SO
Using cloneInto regardless as it's less "work" done in the content script thread
=> feat(ext): polyfill via document events rather than posting window messages

packages/coil-extension/CHANGELOG.md, packages/coil-extension/manifest.json, packages/coil-extension/package.json, packages/coil-extension/scripts/reinstall-six.sh, packages/coil-extension/src/content/util/getAdaptedSite.ts, packages/coil-extension/src/util/openTab.ts, packages/coil-extension/static/popup.html
`https://github.com/coilhq/web-monetization-projects/compare/coil-extension@0.0.51...219fca3461f8e718958ed70154d0338017bcf33c
- ![image](https://user-images.githubusercontent.com/525211/66626655-3c3aae80-ec23-11e9-981a …
=> chore(coil-extension): bump version to 0.0.52

packages/coil-extension/src/popup/Index.tsx, packages/coil-extension/src/popup/components/AccountBar.tsx, packages/coil-extension/src/popup/components/CoilPopup.tsx, packages/coil-extension/src/popup/components/CoilViews.tsx, packages/coil-extension/src/popup/components/LoggedOut.tsx, packages/coil-extension/src/popup/components/MonetizationAnimation.tsx, packages/coil-extension/src/popup/components/MonetizedPage.tsx, packages/coil-extension/src/popup/components/PaidViews.tsx, packages/coil-extension/src/popup/components/Status.tsx, packages/coil-extension/src/popup/components/StreamControls.tsx, packages/coil-extension/src/popup/components/TipButton.tsx, packages/coil-extension/src/popup/components/UnmonetizedPage.tsx, packages/coil-extension/src/popup/components/Unsubscribed.tsx, packages/coil-extension/src/popup/components/Unverified.tsx, packages/coil-extension/src/popup/components/WebMonetizedBar.tsx, packages/coil-extension/src/popup/context/popupHostContext.ts, packages/coil-extension/src/popup/context/storeContext.ts, packages/coil-extension/src/popup/mocks/loadMockedStates.tsx, packages/coil-extension/src/popup/popup.tsx, packages/coil-extension/src/popup/services/PopupState.ts, packages/coil-extension/src/popup/types.ts
- Refactor popup which passed down a context prop everywhere to use React context providers/consumers. 
- Split PopupContext into PopupHost and Store contexts. 
- Add "events" (EventEmitter) to PopupHost to support multiple instances of a popup in a page (styling aid)
- Remove extension message listeners for `localStorageUpdate` messages (*to support Safari*, as per #1340 )
- Listen to "storage" event on new "events" bus in PopupHost
- Extension Host: bind to window "storage" event then proxy to `events` bus
- Mock Host: emit mock "storage" events directly to trigger payment animation with updated monetizationTotal
- Add useStoreState hook to create Store to pass as prop to StoreContext.Provider
- Parameterized with get only (JSON parsing) Storage wrapper and PopupHost 
- listens for …
=> feat(coil-extension): refactor popup

packages/coil-extension/manifest.json, packages/coil-extension/src/background/services/BackgroundFramesService.ts, packages/coil-extension/src/background/services/BackgroundScript.ts, packages/coil-extension/src/popup/popup.tsx, packages/coil-extension/src/types/commands.ts, packages/webexts-build-utils/src/makeWebpackConfig.ts, packages/webexts-build-utils/src/manifestPermissions.ts
Update of https://github.com/coilhq/web-monetization-projects/pull/1340
* Requires "tabs" permission:
Chrome (and to a lesser extent, Firefox) grants many "tabs" permissions
implicitly via "<all_urls>". Safari does not. This is required for using
chrome.tabs to search for an already open tab via url and select it.
via `export WEXT_MANIFEST_PERMISSIONS='["+tabs"]'`
=> feat(coil-extension): support Safari via workarounds

.circleci/config.yml, packages/web-monetization-types/package.json
Closes #1960 
Add a job to publish web-monetization-types behind an approval job.
Requires NPM_AUTH_TOKEN env var to be set securely in Circle UI
=> feat(ci): add publish-packages job

packages/coil-extension/CHANGELOG.md, packages/coil-extension/manifest.json, packages/coil-extension/package.json, packages/coil-extension/src/background/background.ts, packages/coil-extension/src/background/services/BackgroundScript.ts, packages/coil-extension/src/popup/components/HeaderFooterLayout.tsx, packages/coil-extension/test/fixtures/event-logger.html
- **TESTERS NOTE** We published 0.0.52 only to Samsung, so unfortunately we'll skip a version, but it shouldn't be a problem
`https://github.com/coilhq/web-monetization-projects/compare/coil-extension@0.0.52...5abbf1e47b8b69ef2cf0a62a75f4a97e853f4bb5`
- ![image](https://user-images.githubusercontent.com/525211/66626576-f4b42280 …
=> chore(coil-extension): bump version to 0.0.53

.pnp.cjs, .yarnrc.yml, packages/coil-extension/package.json, packages/coil-extension/scripts/publish-coildev-chrome-store.sh, packages/interledger-minute-extension/package.json, yarn.lock
```
Error: @wext/shipit tried to access .bin, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.
Required package: .bin (via ".bin/webstore")
Required by: @wext/shipit@npm:0.2.1 (via /Users/nicholasdudfield/projects/web-monetization/.yarn/cache/@wext-shipit-npm-0.2.1-0aefb3f515-22e62eeee6.zip/node_modules/@wext/shipit/lib/)
```
see: https://githubmemory.com/repo/prisma/codemods/issues/23
TODO:
=> chore(coil-extension): add publish:dev, publish:preview yarn scripts

.circleci/config.yml, .pnp.cjs, packages/coil-extension/package.json, packages/coil-extension/src/background/services/ActiveTabLogger.ts, packages/coil-extension/src/background/services/BackgroundScript.ts, packages/coil-extension/src/background/services/TabStates.ts, packages/coil-extension/src/types/TabState.ts, packages/coil-extension/test/fixtures/multiple-tags-link-first.html, packages/coil-extension/test/fixtures/multiple-tags-meta-first.html, packages/coil-extension/test/puppeteer/multiple-tags-test.ts, packages/coil-puppeteer-utils/src/lib/testMonetization.ts, packages/webmonetization-polyfill-utils/src/lib/MonetizationTagObserver.ts, yarn.lock
Handles case where tags are seen in quick succession such as (but not limited to) :
* page load, where there is a <meta> tag, then a <link> tag
When this happens, stopMonetization is called on the content script side BEFORE the background page has a chance to send the initial optimistic `pending` event. With this change, the pending event from the background page will be tagged with a requestId and ignored on the content script side when it finally arrives.
https://github.com/coilhq/web-monetization-projects/blob/d3c533c84d5565875432fae5db2894b3f4a3305e/packages/coil-extension/src/content/services/ContentScript.ts#L79-L84
https://github.com/coilhq/web-monetization-projects/blob/d3c533c84d5565875432fae5db2894b3f4a3305e/packages/coil-extension/src/content/services/ContentScript.ts#L65-L75 …
=> fix(coil-extension): better handle quick change of tags

packages/coil-extension/CHANGELOG.md, packages/coil-extension/docs/release-checklist.md, packages/coil-extension/manifest.json, packages/coil-extension/package.json, packages/coil-extension/six-apktool-decoded/apktool.yml, packages/coil-extension/src/background/services/ActiveTabLogger.ts, packages/coil-extension/src/background/services/BackgroundScript.ts, packages/coil-extension/src/background/services/TabStates.ts, packages/coil-extension/src/content/services/ContentScript.ts, packages/coil-extension/src/types/commands.ts, packages/coil-extension/test/fixtures/event-logger.html, packages/coil-oauth-scripts/src/bin/coil-it.ts
`https://github.com/coilhq/web-monetization-projects/compare/coil-extension@0.0.48...8f359e45f843a4f9a01c090a02e73519413d900b`
- Use `adb` to install Samsung Internet Extensions
- be sure to kill the browser and delete shared settings to be sure correct addon is tested
- see code in `scripts/reinstall-six.sh`
- ![image](https://user-images.githubusercontent.com/525211/71150879-28d04300-2265-11ea-96da-7d7 …
=> chore(coil-extension): bump version to 0.0.56

packages/coil-extension/src/popup/Index.tsx, packages/coil-extension/src/popup/NewExtension.tsx, packages/coil-extension/src/popup/components/AmountInput.tsx, packages/coil-extension/src/popup/components/Header.tsx, packages/coil-extension/src/popup/components/HotkeyAmountButtons.tsx, packages/coil-extension/src/popup/components/IncDecButton.tsx, packages/coil-extension/src/popup/components/RandomThankYouMessage.tsx, packages/coil-extension/src/popup/components/TipWarning.tsx, packages/coil-extension/src/popup/components/views/Router.tsx, packages/coil-extension/src/popup/components/views/SettingsView.tsx, packages/coil-extension/src/popup/components/views/TipCompleteView.tsx, packages/coil-extension/src/popup/components/views/TipConfirmView.tsx, packages/coil-extension/src/popup/components/views/TipRouter.tsx, packages/coil-extension/src/popup/components/views/TipView.tsx, packages/coil-extension/src/popup/components/views/ViewRouter.tsx, packages/coil-extension/src/popup/context/tipContext.tsx, packages/coil-extension/src/shared-theme/colors.ts
resolves: COIL-1640
- Updated the styles of the tipping views to match the figma
- Removed the tipping views from `TipRouter` and put each page into the `Router`
- Replaced use of local state with a `tipContext` for the tip views
- Removed tipping from legacy UI -> temporarily using `tipping-beta` feature flag
***note: Fabi has been updating the artwork assets. When they are finalized I will be updating the extension artwork***
=> feat: update tipping views

.circleci/config.yml
Publishing the staging chrome extension as an artifact.  This will allow the coil workflow to consume the artifact for its own e2e tests.
* builds the extension using the `build-staging` command.  e2e tests will be run in staging
* waits for tests to pass before publishing the artifact.  Don't want bad builds.
* Only builds for main
Artifacts are stored for 30 days.
Downloading the artifact is discussed in the following article:
https://circleci.com/docs/2.0/artifacts/#downloading-all-artifacts-for-a-build-on-circleci
=> test: publish staging extension for e2e tests

packages/coil-extension/src/background/services/TippingService.ts, packages/coil-extension/src/background/util/formatters.ts, packages/coil-extension/src/popup/components/AmountInput.tsx, packages/coil-extension/src/popup/components/HotkeyAmountButtons.tsx, packages/coil-extension/src/popup/components/IncDecButton.tsx, packages/coil-extension/src/popup/components/views/TipConfirmView.tsx, packages/coil-extension/src/popup/components/views/TipView.tsx, packages/coil-extension/src/popup/context/tipContext.tsx, packages/coil-extension/src/popup/mocks/loadMockedStates.tsx, packages/coil-extension/src/types/commands.ts, packages/coil-extension/src/types/user.ts, packages/coil-extension/src/util/calculateMaxAllowableTip.ts, packages/coil-extension/test/jest/calculateMaxAllowableTip.test.ts
resolves: COIL-1712
This fixes the issue of the tipping limit not being set to $0 on when a user switches from a webmo'd tab to a non webmo'd tab.
=> feat: fix max tip amount

packages/coil-extension/src/popup/components/TipAmountFeedback.tsx
resolves: COIL-1714
Update the tip credits feedback to be static and reflect the users current tip credit balance instead of recalculating based on the current tip amount
=> feat: updated the feedback for tip credits

packages/coil-extension/src/popup/components/views/TipConfirmView.tsx, packages/coil-extension/src/popup/components/views/TipView.tsx, packages/coil-extension/src/popup/context/tipContext.tsx
resolves: COIL-1729
- removed the header from the tip confirm view
- The display of the initial tip amount now sets to zero if the max allowed tip is less than $1
- The submit button also checks to see if the tip amount is somehow set to a value below the minimum tip limit and will be disabled
=> fix: fixed tip display to 0 and submit button

packages/coil-client/src/queries/tipSettings.ts, packages/coil-extension/src/background/services/TippingService.ts
resolves: COIL-1786
Removed extension throwing error if `whaomi > tipping` returned null. Fixed nested destructures on null values
=> fix: query error for tip settings

packages/coil-extension/src/popup/Index.tsx, packages/coil-extension/src/popup/components/views/TipCompleteView.tsx, packages/coil-extension/src/popup/components/views/TipConfirmView.tsx, packages/coil-extension/src/popup/context/tipContext.tsx
Updates the tipContext when the user object in localStorage is updated. Also added a value for the final tip amount so that the TipComplete view would not be impacted by the localStorage update. 
The user can now submit a tip with tip credits and try to tip a second time with the "Available tip credits" being properly updated without having to close the extension and reopen it. 
related to COIL-1737
=> fix: update tip credit balance and final tip amount after tip

packages/coil-client/src/index.ts, packages/coil-extension/CHANGELOG.md, packages/coil-extension/docs/release-checklist.md, packages/coil-extension/package.json, packages/coil-extension/six-apktool-decoded/apktool.yml, packages/coil-extension/src/background/services/AuthService.ts, packages/coil-extension/src/background/services/TippingService.ts, packages/coil-extension/src/background/services/formatTipSettings.util.ts, packages/coil-extension/src/content/services/ContentScript.ts, packages/coil-extension/src/popup/components/views/StreamingCoilDiscoverView.tsx, packages/coil-extension/src/popup/components/views/StreamingCoilView.tsx, packages/coil-extension/src/popup/components/views/StreamingNoMembershipView.tsx, packages/coil-extension/src/popup/components/views/StreamingNotWebMonetizedView.tsx, packages/coil-extension/src/popup/components/views/StreamingWebMonitizedView.tsx, packages/coil-extension/src/popup/components/views/TipNonMonetizedView.tsx, packages/coil-extension/src/popup/components/views/TipView.tsx, packages/coil-extension/src/types/user.ts
`https://github.com/coilhq/web-monetization-projects/compare/coil-extension@0.0.56...nd-update-version-0-0-57-2022-02-08
(substitute release branch name for "main")
- Some web stores will require the submission of source files.
- So far, zipping the `coil-extension` folder (instead of zipping at the project root)
has given us the least trouble with passing review.
- For example, `zip -r coil-extension.zip coil-extension/`
- `node_modules` should be deleted prior to zipping the source files.
make sense.
- For …
=> chore(coil-extension): bump version to 0.0.57

packages/coil-client/src/index.ts, packages/coil-extension/docs/release-checklist.md, packages/coil-extension/src/background/services/AuthService.ts, packages/coil-extension/src/background/services/TippingService.ts, packages/coil-extension/src/background/services/formatTipSettings.util.ts, packages/coil-extension/src/content/services/ContentScript.ts, packages/coil-extension/src/popup/components/views/StreamingCoilDiscoverView.tsx, packages/coil-extension/src/popup/components/views/StreamingCoilView.tsx, packages/coil-extension/src/popup/components/views/StreamingNoMembershipView.tsx, packages/coil-extension/src/popup/components/views/StreamingNotWebMonetizedView.tsx, packages/coil-extension/src/popup/components/views/StreamingWebMonitizedView.tsx, packages/coil-extension/src/popup/components/views/TipNonMonetizedView.tsx, packages/coil-extension/src/popup/components/views/TipView.tsx, packages/coil-extension/src/types/user.ts
* Do whoami and tipData queries in parallel from AuthService
* Only play streaming animation if have recent packet (<= 5s)
* Don't show old extension views while refreshing page (due to slow tip queries)
* Handle null tipping response in AuthService
* Update titles and copy
=> feat(coil-extension): collection of fixes

packages/coil-extension/src/popup/components/views/TipConfirmView.tsx
resolves: COIL-1805
redirect back to TipView if `tipPreview` errors out due to user leaving the flow.
=> feat: redirect back to tip view if tip preview fails

packages/coil-client/src/queries/tip.ts
resolves: COIL-1875
the `tip` mutation was manually throwing `graphql query failed. status=${code} query=\${tipQuery}\` if the result was not a success, updated it to pass the response message as the error if it exists otherwise just a generic "Something went wrong"
=> fix: tip graphql error

packages/coil-extension/src/popup/components/AmountInput.test.ts, packages/coil-extension/src/popup/components/AmountInput.tsx, packages/coil-extension/src/popup/components/TipAmountFeedback.tsx, packages/coil-extension/src/popup/context/tipContext.tsx
resolves: COIL-1920
limits manual input of tips to whole numbers and does not allow users to input fractional amounts.
=> feat: disallow fractional inputs

packages/coil-extension/CHANGELOG.md, packages/coil-extension/manifest.json, packages/coil-extension/package.json, packages/coil-extension/six-apktool-decoded/apktool.yml
- You can compare this branch against last release via:
- https://github.com/coilhq/web-monetization-projects/compare/coil-extension@0.0.57...nd-bump-version-0-58-2022-02-25
=> chore(coil-extension): bump version to 0.0.58

packages/coil-extension/CHANGELOG.md, packages/coil-extension/docs/release-checklist.md, packages/coil-extension/manifest.json, packages/coil-extension/package.json, packages/coil-extension/six-apktool-decoded/apktool.yml, packages/coil-extension/test/fixtures/event-logger.html
https://github.com/coilhq/web-monetization-projects/compare/coil-extension@0.0.58...main
(substitute release branch name for "main")
make sense.
- Use `adb` to install Samsung Internet Extensions
- be sure to kill the browser and delete shared settings to be sure correct addon is tested
- see code in `scripts/reinstall-six.sh` …
=> chore(coil-extension): bump version to 0.0.59

packages/coil-extension/CHANGELOG.md, packages/coil-extension/manifest.json, packages/coil-extension/package.json, packages/coil-extension/six-apktool-decoded/apktool.yml
- https://github.com/coilhq/web-monetization-projects/compare/coil-extension@0.0.59...nd-bump-version-60-2022-08-11
makes sense.
- Use `adb` to install Samsung Internet Extensions
- be sure to kill the browser and delete shared settings to be sure correct addon is tested
- see code in `scripts/reinstall-six.sh`
- …
=> chore(coil-extension): bump version to 0.0.60

.github/workflows/archive-extension-source-code.yml, packages/coil-extension/CHANGELOG.md, packages/coil-extension/manifest.json, packages/coil-extension/package.json, packages/coil-extension/six-apktool-decoded/apktool.yml
- https://github.com/coilhq/web-monetization-projects/compare/coil-extension@0.0.60...nd-bump-version-61-2022-09-15
makes sense.
- Use `adb` to install Samsung Internet Extensions
- be sure to kill the browser and delete shared settings to be sure correct addon is tested
- see code in `scripts/reinstall-six.sh`
- …
=> chore(coil-extension): bump version to 0.0.61

packages/coil-extension/src/popup/components/views/SettingsView.tsx
This PR corrects the typo in the extension that routes to `acount` instead of `account`.  It appears that it's already fixed on the backend as you can see that when you arrive at `acount` you're redirected to `account`.  This PR should make that redirection unnecessary. The GIF below illustrates what happens now, should this PR be merged, the redirect you see at present should not happen.
=> fix: acount corrected to account

packages/coil-extension/CHANGELOG.md, packages/coil-extension/manifest.json, packages/coil-extension/package.json
See [changes](https://github.com/coilhq/web-monetization-projects/compare/coil-extension@0.0.62...nd-remove-macos-workaround-2022-10-04)
=> chore(coil-extension): bump version to 0.0.63
